### PR TITLE
Add support for /dev/video 

### PR DESCRIPTION
**Pull request by mbach04**
Tested this locally with a MacBook Facetime cam, passed into an ubuntu instance as /dev/video0 successfully.
Never done cpp, so please feel free to comment/correct my work.

### CODE REVIEW

**Comment by mbach04** [comment]
Got it. Thanks

**Comment by Ullaakut** [comment]
OK don't worry about the CI not passing, I just saw that Travis CI disables encrypted variables in PR builds. I will make an issue and fix this asap.

**Comment by Ullaakut** [comment]
Fixed the CI and force rebased your branch, the CI should work flawlessly now!

Still waiting for an approval from @Gegonz though! (or anyone with a working linux video device to test the PR, which is not my case)

**Comment by Gegonz** [comment]
I can't test as I don't have /dev/video0 on my laptop but this seems good to me now.

**Pull request merged**
